/**
 * mines-data.js - Mine-level operational data for premium mining analysis.
 * Sources: company FY2024 annual reports / MD&A unless otherwise noted (BHP FY2025 ended June 2025).
 * For educational / illustrative use; verify figures against primary filings.
 */

var MINES_DATA = {
  "FCX": [
    {
      name: "Grasberg",
      location: "Papua",
      country: "Indonesia",
      ownership_pct: 48.76,
      type: "Underground",
      primary_metal: "copper",
      metals: ["copper", "gold", "silver"],
      status: "Operating",
      production: { copper_mlbs: 1800, gold_koz: 1861 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: 1.64, net_cash_cost_per_lb: -0.28 },
      reserves: { copper_blbs: 27, gold_moz: 22.4 },
      mine_life_yrs: 17,
      notes: "World's largest copper-gold mine; underground DMLZ + GBC; mine life to 2041."
    },
    {
      name: "Cerro Verde",
      location: "Arequipa region",
      country: "Peru",
      ownership_pct: 55.08,
      type: "Open pit",
      primary_metal: "copper",
      metals: ["copper", "molybdenum"],
      status: "Operating",
      production: { copper_mlbs: 949, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: 2.63, net_cash_cost_per_lb: 2.46 },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "FY2024 Cu 949 mlbs; Mo ~20 mlbs; segment cash $2.63/lb, net $2.46/lb; SA reserves 28.4 Blbs Cu company-wide."
    },
    {
      name: "El Abra",
      location: "El Loa",
      country: "Chile",
      ownership_pct: 51,
      type: "Open pit (SX-EW)",
      primary_metal: "copper",
      metals: ["copper"],
      status: "Operating",
      production: { copper_mlbs: 219, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Open-pit SX-EW copper."
    },
    {
      name: "Morenci",
      location: "Greenlee County, AZ",
      country: "United States",
      ownership_pct: 72,
      type: "Open pit",
      primary_metal: "copper",
      metals: ["copper", "molybdenum"],
      status: "Operating",
      production: { copper_mlbs: 505, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: 3.46, net_cash_cost_per_lb: 3.11 },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Part of NA segment; cash $3.46/lb, net $3.11/lb FY2024."
    },
    {
      name: "Bagdad",
      location: "Yavapai County, AZ",
      country: "United States",
      ownership_pct: 100,
      type: "Open pit",
      primary_metal: "copper",
      metals: ["copper", "molybdenum"],
      status: "Operating",
      production: { copper_mlbs: 146, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Expansion potential +200-250 mlbs/yr; 80+ year mine life cited."
    },
    {
      name: "Safford / Lone Star",
      location: "Graham/Greenlee County, AZ",
      country: "United States",
      ownership_pct: 100,
      type: "Open pit",
      primary_metal: "copper",
      metals: ["copper"],
      status: "Operating",
      production: { copper_mlbs: 249, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Includes Lone Star development area."
    },
    {
      name: "Sierrita",
      location: "Pima County, AZ",
      country: "United States",
      ownership_pct: 100,
      type: "Open pit",
      primary_metal: "copper",
      metals: ["copper", "molybdenum"],
      status: "Operating",
      production: { copper_mlbs: 165, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Integrated concentrator operations."
    },
    {
      name: "Chino",
      location: "Grant County, NM",
      country: "United States",
      ownership_pct: 100,
      type: "Open pit",
      primary_metal: "copper",
      metals: ["copper", "molybdenum"],
      status: "Operating",
      production: { copper_mlbs: 133, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Southwest copper operations."
    },
    {
      name: "Tyrone",
      location: "Grant County, NM",
      country: "United States",
      ownership_pct: 100,
      type: "Open pit",
      primary_metal: "copper",
      metals: ["copper"],
      status: "Operating",
      production: { copper_mlbs: 43, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Southwest copper operations."
    },
    {
      name: "Miami",
      location: "Gila County, AZ",
      country: "United States",
      ownership_pct: 100,
      type: "Open pit",
      primary_metal: "copper",
      metals: ["copper"],
      status: "Operating",
      production: { copper_mlbs: 9, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Includes smelter complex."
    },
    {
      name: "Atlantic Copper",
      location: "Huelva",
      country: "Spain",
      ownership_pct: 100,
      type: "Smelter / refinery",
      primary_metal: "copper",
      metals: ["copper"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "~300 kt/yr cathode capacity; smelting and refining."
    }
  ],
  "GOLD": [
    {
      name: "Carlin Complex",
      location: "Nevada",
      country: "United States",
      ownership_pct: 61.5,
      type: "Open pit / underground",
      primary_metal: "gold",
      metals: ["gold"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 775 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: 9.5 },
      mine_life_yrs: null,
      notes: "NGM JV; attrib 775 koz; AISC $1730/oz, cash $1187/oz FY2024."
    },
    {
      name: "Cortez Complex",
      location: "Nevada",
      country: "United States",
      ownership_pct: 61.5,
      type: "Open pit / underground",
      primary_metal: "gold",
      metals: ["gold"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 444 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: 8.3 },
      mine_life_yrs: null,
      notes: "Attrib 444 koz; AISC $1441/oz, cash $1046/oz FY2024."
    },
    {
      name: "Turquoise Ridge",
      location: "Nevada",
      country: "United States",
      ownership_pct: 61.5,
      type: "Underground",
      primary_metal: "gold",
      metals: ["gold"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 304 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: 8.9 },
      mine_life_yrs: null,
      notes: "Attrib 304 koz; AISC $1466/oz, cash $1238/oz FY2024."
    },
    {
      name: "Phoenix (NGM)",
      location: "Nevada",
      country: "United States",
      ownership_pct: 61.5,
      type: "Open pit",
      primary_metal: "gold",
      metals: ["gold", "copper"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 127 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: 1.9 },
      mine_life_yrs: null,
      notes: "Attrib 127 koz; AISC $1031/oz, cash $765/oz FY2024."
    },
    {
      name: "Pueblo Viejo",
      location: "Sanchez Ramirez",
      country: "Dominican Republic",
      ownership_pct: 60,
      type: "Open pit",
      primary_metal: "gold",
      metals: ["gold", "silver"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 352 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: 12 },
      mine_life_yrs: null,
      notes: "Attrib 352 koz; AISC $1323/oz, cash $1005/oz FY2024."
    },
    {
      name: "Loulo-Gounkoto",
      location: "Kayes region",
      country: "Mali",
      ownership_pct: 80,
      type: "Open pit / underground",
      primary_metal: "gold",
      metals: ["gold"],
      status: "Suspended",
      production: { copper_mlbs: null, gold_koz: 578 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: 7.3 },
      mine_life_yrs: null,
      notes: "Attrib 578 koz FY2024; AISC $1304/oz, cash $828/oz; operations suspended Jan 2025."
    },
    {
      name: "Kibali",
      location: "Haut-Uele",
      country: "Democratic Republic of the Congo",
      ownership_pct: 45,
      type: "Open pit / underground",
      primary_metal: "gold",
      metals: ["gold"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 309 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: 4.6 },
      mine_life_yrs: null,
      notes: "Attrib 309 koz; AISC $1123/oz, cash $905/oz FY2024."
    },
    {
      name: "North Mara",
      location: "Mara Region",
      country: "Tanzania",
      ownership_pct: 84,
      type: "Open pit",
      primary_metal: "gold",
      metals: ["gold"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 265 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: 2.9 },
      mine_life_yrs: null,
      notes: "Attrib 265 koz; AISC $1274/oz FY2024."
    },
    {
      name: "Bulyanhulu",
      location: "Kahama",
      country: "Tanzania",
      ownership_pct: 84,
      type: "Underground",
      primary_metal: "gold",
      metals: ["gold", "silver"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 168 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: 3.8 },
      mine_life_yrs: null,
      notes: "Attrib 168 koz; AISC $1420/oz FY2024."
    },
    {
      name: "Tongon",
      location: "Boundiali",
      country: "Ivory Coast",
      ownership_pct: 89.7,
      type: "Open pit",
      primary_metal: "gold",
      metals: ["gold"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 148 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: 0.62 },
      mine_life_yrs: null,
      notes: "Attrib 148 koz; AISC $1867/oz FY2024."
    },
    {
      name: "Veladero",
      location: "San Juan",
      country: "Argentina",
      ownership_pct: 50,
      type: "Heap leach",
      primary_metal: "gold",
      metals: ["gold", "silver"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 252 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: 1.6 },
      mine_life_yrs: null,
      notes: "Attrib 252 koz; AISC $1334/oz FY2024."
    },
    {
      name: "Porgera",
      location: "Enga",
      country: "Papua New Guinea",
      ownership_pct: 24.5,
      type: "Open pit / underground",
      primary_metal: "gold",
      metals: ["gold", "silver"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 46 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: 1.5 },
      mine_life_yrs: null,
      notes: "Attrib 46 koz; AISC $1666/oz FY2024."
    },
    {
      name: "Lumwana",
      location: "Solwezi",
      country: "Zambia",
      ownership_pct: 100,
      type: "Open pit",
      primary_metal: "copper",
      metals: ["copper", "gold"],
      status: "Operating",
      production: { copper_mlbs: 271, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Cu 271 mlbs; AISC $3.85/lb Cu FY2024."
    },
    {
      name: "Reko Diq",
      location: "Balochistan",
      country: "Pakistan",
      ownership_pct: 50,
      type: "Development",
      primary_metal: "copper",
      metals: ["copper", "gold"],
      status: "Development",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: 13 },
      mine_life_yrs: null,
      notes: "World-class development; reserves ~13 Moz Au + 7.3 Mt Cu (company disclosure)."
    }
  ],
  "NEM": [
    {
      name: "Boddington",
      location: "Western Australia",
      country: "Australia",
      ownership_pct: 100,
      type: "Open pit",
      primary_metal: "gold",
      metals: ["gold", "copper"],
      status: "Operating",
      production: { copper_mlbs: 163, gold_koz: 590 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: 10.8 },
      mine_life_yrs: 18,
      notes: "Au 590 koz, Cu 163 mlbs; AISC $1288/oz FY2024."
    },
    {
      name: "Tanami",
      location: "Northern Territory",
      country: "Australia",
      ownership_pct: 100,
      type: "Underground",
      primary_metal: "gold",
      metals: ["gold"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 408 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: 5.1 },
      mine_life_yrs: 12,
      notes: "AISC $1281/oz FY2024."
    },
    {
      name: "Cadia",
      location: "New South Wales",
      country: "Australia",
      ownership_pct: 100,
      type: "Underground",
      primary_metal: "gold",
      metals: ["gold", "copper"],
      status: "Operating",
      production: { copper_mlbs: 384, gold_koz: 464 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: 14.1 },
      mine_life_yrs: 30,
      notes: "Au 464 koz, Cu 384 mlbs; AISC $1048/oz; Cu reserves ~3.1 Mt FY2024."
    },
    {
      name: "Lihir",
      location: "New Ireland",
      country: "Papua New Guinea",
      ownership_pct: 100,
      type: "Open pit",
      primary_metal: "gold",
      metals: ["gold", "silver"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 614 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: 15.8 },
      mine_life_yrs: 26,
      notes: "AISC $1512/oz FY2024."
    },
    {
      name: "Ahafo",
      location: "Brong-Ahafo",
      country: "Ghana",
      ownership_pct: 100,
      type: "Open pit / underground",
      primary_metal: "gold",
      metals: ["gold"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 798 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: 9.2 },
      mine_life_yrs: 12,
      notes: "AISC $1072/oz FY2024."
    },
    {
      name: "Akyem",
      location: "Eastern",
      country: "Ghana",
      ownership_pct: 100,
      type: "Open pit",
      primary_metal: "gold",
      metals: ["gold"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 204 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: 0.9 },
      mine_life_yrs: 4,
      notes: "AISC $1816/oz FY2024."
    },
    {
      name: "PeÃ±asquito",
      location: "Zacatecas",
      country: "Mexico",
      ownership_pct: 100,
      type: "Open pit",
      primary_metal: "gold",
      metals: ["gold", "silver", "zinc", "lead"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 299 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: 4.1 },
      mine_life_yrs: 14,
      notes: "Au 299 koz, Ag 33 Moz, Zn 258 kt; AISC $984/oz FY2024."
    },
    {
      name: "Merian",
      location: "Sipaliwini",
      country: "Suriname",
      ownership_pct: 75,
      type: "Open pit",
      primary_metal: "gold",
      metals: ["gold"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 205 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: 4.1 },
      mine_life_yrs: 20,
      notes: "Attrib 205 koz; AISC $1852/oz FY2024."
    },
    {
      name: "Cerro Negro",
      location: "Santa Cruz",
      country: "Argentina",
      ownership_pct: 100,
      type: "Underground",
      primary_metal: "gold",
      metals: ["gold", "silver"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 238 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: 3.2 },
      mine_life_yrs: 13,
      notes: "AISC $1631/oz FY2024."
    },
    {
      name: "Yanacocha",
      location: "Cajamarca",
      country: "Peru",
      ownership_pct: 100,
      type: "Heap leach",
      primary_metal: "gold",
      metals: ["gold", "silver"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 354 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: 5.3 },
      mine_life_yrs: 15,
      notes: "AISC $1196/oz FY2024."
    },
    {
      name: "Brucejack",
      location: "British Columbia",
      country: "Canada",
      ownership_pct: 100,
      type: "Underground",
      primary_metal: "gold",
      metals: ["gold", "silver"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 258 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: 1.9 },
      mine_life_yrs: 7,
      notes: "AISC $1603/oz FY2024."
    },
    {
      name: "Red Chris",
      location: "British Columbia",
      country: "Canada",
      ownership_pct: 70,
      type: "Open pit",
      primary_metal: "gold",
      metals: ["gold", "copper"],
      status: "Operating",
      production: { copper_mlbs: 115, gold_koz: 40 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: 3.7 },
      mine_life_yrs: 93,
      notes: "Attrib production; AISC $1607/oz; Cu reserves ~1.0 Mt FY2024."
    }
  ],
  "SCCO": [
    {
      name: "Buenavista",
      location: "Sonora",
      country: "Mexico",
      ownership_pct: 100,
      type: "Open pit",
      primary_metal: "copper",
      metals: ["copper", "zinc", "silver"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Largest mine by volume; zinc concentrator ramped 2024; FY2024 company Cu 973,851 t (2,147 mlbs)."
    },
    {
      name: "La Caridad",
      location: "Sonora",
      country: "Mexico",
      ownership_pct: 100,
      type: "Open pit",
      primary_metal: "copper",
      metals: ["copper", "molybdenum", "silver"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Integrated smelter and refinery; consolidated cash cost $0.89/lb Cu net of by-products FY2024."
    },
    {
      name: "IMMSA underground mines",
      location: "Multiple",
      country: "Mexico",
      ownership_pct: 100,
      type: "Underground",
      primary_metal: "zinc",
      metals: ["zinc", "lead", "silver"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Charcas, San Martin, Santa Barbara, San Luis, Taxco â€” zinc/lead/silver focused."
    },
    {
      name: "Toquepala",
      location: "Tacna",
      country: "Peru",
      ownership_pct: 100,
      type: "Open pit",
      primary_metal: "copper",
      metals: ["copper", "molybdenum"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Southern Peru copper cluster."
    },
    {
      name: "Cuajone",
      location: "Moquegua",
      country: "Peru",
      ownership_pct: 100,
      type: "Open pit",
      primary_metal: "copper",
      metals: ["copper", "molybdenum", "silver"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Southern Peru copper cluster."
    },
    {
      name: "TÃ­a MarÃ­a",
      location: "Islay",
      country: "Peru",
      ownership_pct: 100,
      type: "Development (SX-EW)",
      primary_metal: "copper",
      metals: ["copper"],
      status: "Development",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Greenfield SX-EW ~120,000 t/yr cathode capacity; capex ~$1.8B; production targeted ~2027."
    },
    {
      name: "Los Chancas",
      location: "ApurÃ­mac",
      country: "Peru",
      ownership_pct: 100,
      type: "Development",
      primary_metal: "copper",
      metals: ["copper", "molybdenum"],
      status: "Development",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Copper-moly project; ~130,000 t/yr Cu target; capex ~$2.6B; production targeted ~2031."
    }
  ],
  "TECK": [
    {
      name: "Highland Valley Copper",
      location: "British Columbia",
      country: "Canada",
      ownership_pct: 100,
      type: "Open pit",
      primary_metal: "copper",
      metals: ["copper", "molybdenum"],
      status: "Operating",
      production: { copper_mlbs: 226, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: 4,
      notes: "Cu 102,400 t (226 mlbs); mine life to 2028; copper segment net cash $2.20/lb FY2024."
    },
    {
      name: "Antamina",
      location: "Ancash",
      country: "Peru",
      ownership_pct: 22.5,
      type: "Open pit",
      primary_metal: "copper",
      metals: ["copper", "zinc", "molybdenum", "silver"],
      status: "Operating",
      production: { copper_mlbs: 212, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: 12,
      notes: "Attrib Cu 96,000 t (212 mlbs), Zn 60,000 t; mine life to 2036."
    },
    {
      name: "Quebrada Blanca Phase 2 (QB2)",
      location: "TarapacÃ¡",
      country: "Chile",
      ownership_pct: 60,
      type: "Open pit",
      primary_metal: "copper",
      metals: ["copper", "molybdenum", "silver"],
      status: "Operating",
      production: { copper_mlbs: 459, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Cu 208,000 t (459 mlbs) FY2024; ramped to design rates in 2024."
    },
    {
      name: "Carmen de Andacollo",
      location: "Coquimbo",
      country: "Chile",
      ownership_pct: 90,
      type: "Open pit",
      primary_metal: "copper",
      metals: ["copper", "gold"],
      status: "Operating",
      production: { copper_mlbs: 88, gold_koz: 20.8 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: Cu 39,700 t (88 mlbs), Au 20.8 koz FY2024.,
      notes: ""
    },
    {
      name: "Red Dog",
      location: "Alaska",
      country: "United States",
      ownership_pct: 100,
      type: "Open pit",
      primary_metal: "zinc",
      metals: ["zinc", "lead", "silver"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Zn 555,600 t FY2024; net cash cost $0.39/lb Zn."
    }
  ],
  "HBM": [
    {
      name: "Constancia / Pampacancha",
      location: "Cusco",
      country: "Peru",
      ownership_pct: 100,
      type: "Open pit",
      primary_metal: "copper",
      metals: ["copper", "gold", "silver", "molybdenum"],
      status: "Operating",
      production: { copper_mlbs: 218, gold_koz: 98 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: 17,
      notes: "Cu 99,001 t (218 mlbs), Au 98 koz, Ag 2,708 koz; Peru cash $1.18/lb, sustaining $1.86/lb; AISC $1.88/lb Cu consolidated; mine life to 2041."
    },
    {
      name: "Lalor / New Britannia",
      location: "Manitoba",
      country: "Canada",
      ownership_pct: 100,
      type: "Underground",
      primary_metal: "gold",
      metals: ["gold", "copper", "zinc"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 147 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Au 147 koz; Cu 6,976 t; gold cash cost $606/oz FY2024."
    },
    {
      name: "Stall",
      location: "Manitoba",
      country: "Canada",
      ownership_pct: 100,
      type: "Processing",
      primary_metal: "zinc",
      metals: ["zinc", "gold", "silver"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 67 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Zn 33,339 t; Au 67 koz FY2024."
    },
    {
      name: "Copper Mountain",
      location: "British Columbia",
      country: "Canada",
      ownership_pct: 75,
      type: "Open pit",
      primary_metal: "copper",
      metals: ["copper", "gold", "silver"],
      status: "Operating",
      production: { copper_mlbs: 58, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: 2.74, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Cu 26,406 t (58 mlbs); cash cost $2.74/lb FY2024."
    },
    {
      name: "Copper World",
      location: "Arizona",
      country: "United States",
      ownership_pct: 100,
      type: "Development",
      primary_metal: "copper",
      metals: ["copper"],
      status: "Development",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: 20 },
      mine_life_yrs: Development; ~85,000 t/yr Cu target; ~20-year mine life cited.,
      notes: ""
    }
  ],
  "AEM": [
    {
      name: "Canadian Malartic / Odyssey",
      location: "Quebec",
      country: "Canada",
      ownership_pct: 100,
      type: "Open pit / underground",
      primary_metal: "gold",
      metals: ["gold", "silver"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 656 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "TCC $930/oz FY2024; company 3,485 koz Au, AISC $1,239/oz, 54.3 Moz reserves."
    },
    {
      name: "Detour Lake",
      location: "Ontario",
      country: "Canada",
      ownership_pct: 100,
      type: "Open pit",
      primary_metal: "gold",
      metals: ["gold"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 672 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "TCC $796/oz FY2024."
    },
    {
      name: "Macassa",
      location: "Ontario",
      country: "Canada",
      ownership_pct: 100,
      type: "Underground",
      primary_metal: "gold",
      metals: ["gold"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 279 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "TCC $748/oz FY2024."
    },
    {
      name: "LaRonde Complex",
      location: "Quebec",
      country: "Canada",
      ownership_pct: 100,
      type: "Underground",
      primary_metal: "gold",
      metals: ["gold", "silver", "zinc", "copper"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 307 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "TCC $945/oz FY2024."
    },
    {
      name: "Goldex",
      location: "Quebec",
      country: "Canada",
      ownership_pct: 100,
      type: "Underground",
      primary_metal: "gold",
      metals: ["gold"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 131 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "TCC $923/oz FY2024."
    },
    {
      name: "Meadowbank / Amaruq",
      location: "Nunavut",
      country: "Canada",
      ownership_pct: 100,
      type: "Open pit",
      primary_metal: "gold",
      metals: ["gold", "silver"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 505 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "TCC $938/oz FY2024."
    },
    {
      name: "Meliadine",
      location: "Nunavut",
      country: "Canada",
      ownership_pct: 100,
      type: "Underground",
      primary_metal: "gold",
      metals: ["gold", "silver"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 379 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "TCC $940/oz FY2024."
    },
    {
      name: "Fosterville",
      location: "Victoria",
      country: "Australia",
      ownership_pct: 100,
      type: "Underground",
      primary_metal: "gold",
      metals: ["gold", "antimony"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 225 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "TCC $647/oz FY2024."
    },
    {
      name: "Pinos Altos",
      location: "Chihuahua",
      country: "Mexico",
      ownership_pct: 100,
      type: "Underground",
      primary_metal: "gold",
      metals: ["gold", "silver"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 113 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "TCC $1,530/oz FY2024."
    },
    {
      name: "Kittila",
      location: "Lapland",
      country: "Finland",
      ownership_pct: 100,
      type: "Underground",
      primary_metal: "gold",
      metals: ["gold"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 219 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "TCC $1,031/oz FY2024."
    }
  ],
  "KGC": [
    {
      name: "Fort Knox / Manh Choh",
      location: "Alaska",
      country: "United States",
      ownership_pct: 100,
      type: "Open pit",
      primary_metal: "gold",
      metals: ["gold"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 377 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Combined ~377 AuEq koz; Fort Knox reserves 1.276 Moz + Manh Choh 0.558 Moz (Kinross 70% Manh Choh)."
    },
    {
      name: "Round Mountain",
      location: "Nevada",
      country: "United States",
      ownership_pct: 100,
      type: "Open pit",
      primary_metal: "gold",
      metals: ["gold", "silver"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 215 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: 1.883 },
      mine_life_yrs: null,
      notes: "Au 215 koz; group AISC ~$1,388/oz FY2024."
    },
    {
      name: "Bald Mountain",
      location: "Nevada",
      country: "United States",
      ownership_pct: 100,
      type: "Open pit",
      primary_metal: "gold",
      metals: ["gold", "silver"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 181 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: 1.173 },
      mine_life_yrs: null,
      notes: "Au 181 koz FY2024."
    },
    {
      name: "Paracatu",
      location: "Minas Gerais",
      country: "Brazil",
      ownership_pct: 100,
      type: "Open pit",
      primary_metal: "gold",
      metals: ["gold"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 529 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: 4.887 },
      mine_life_yrs: null,
      notes: "Au 529 koz FY2024."
    },
    {
      name: "La Coipa",
      location: "Atacama",
      country: "Chile",
      ownership_pct: 100,
      type: "Open pit",
      primary_metal: "gold",
      metals: ["gold", "silver"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 246 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: 0.642 },
      mine_life_yrs: null,
      notes: "Au 246 koz FY2024."
    },
    {
      name: "Tasiast",
      location: "Inchiri",
      country: "Mauritania",
      ownership_pct: 100,
      type: "Open pit",
      primary_metal: "gold",
      metals: ["gold"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 622 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: 4.705 },
      mine_life_yrs: null,
      notes: "Au 622 koz FY2024."
    },
    {
      name: "Great Bear",
      location: "Ontario",
      country: "Canada",
      ownership_pct: 100,
      type: "Development",
      primary_metal: "gold",
      metals: ["gold"],
      status: "Development",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "M&I 2.7 Moz + Inferred 3.9 Moz (company disclosure)."
    }
  ],
  "BTG": [
    {
      name: "Fekola",
      location: "Kayes",
      country: "Mali",
      ownership_pct: 80,
      type: "Open pit",
      primary_metal: "gold",
      metals: ["gold"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 393 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Attrib basis; 2025 guidance AISC $1,550-$1,610/oz; consolidated AISC ~$1,465/oz FY2024."
    },
    {
      name: "Masbate",
      location: "Masbate",
      country: "Philippines",
      ownership_pct: 100,
      type: "Open pit",
      primary_metal: "gold",
      metals: ["gold", "silver"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 194 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "2025 AISC guidance $1,310-$1,370/oz."
    },
    {
      name: "Otjikoto",
      location: "Otjiwarongo",
      country: "Namibia",
      ownership_pct: 90,
      type: "Open pit",
      primary_metal: "gold",
      metals: ["gold"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 198 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "2025 AISC guidance $980-$1,040/oz."
    },
    {
      name: "Goose / Back River",
      location: "Nunavut",
      country: "Canada",
      ownership_pct: 100,
      type: "Development",
      primary_metal: "gold",
      metals: ["gold"],
      status: "Development",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "First gold Q2 2025; ~310 koz/yr average production target."
    },
    {
      name: "Gramalote",
      location: "Antioquia",
      country: "Colombia",
      ownership_pct: 100,
      type: "Development",
      primary_metal: "gold",
      metals: ["gold"],
      status: "Development",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Development project; ~234 koz/yr first five years (company study)."
    }
  ],
  "GFI": [
    {
      name: "St Ives",
      location: "Western Australia",
      country: "Australia",
      ownership_pct: 100,
      type: "Open pit / underground",
      primary_metal: "gold",
      metals: ["gold"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Open pit and underground operations; ~2.07 Moz AuEq attributable FY2024."
    },
    {
      name: "Granny Smith",
      location: "Western Australia",
      country: "Australia",
      ownership_pct: 100,
      type: "Underground",
      primary_metal: "gold",
      metals: ["gold"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Underground gold mine."
    },
    {
      name: "Agnew",
      location: "Western Australia",
      country: "Australia",
      ownership_pct: 100,
      type: "Underground",
      primary_metal: "gold",
      metals: ["gold"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Underground operations."
    },
    {
      name: "South Deep",
      location: "Gauteng",
      country: "South Africa",
      ownership_pct: 100,
      type: "Underground",
      primary_metal: "gold",
      metals: ["gold", "uranium"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Deep mechanised gold mine."
    },
    {
      name: "Tarkwa",
      location: "Western",
      country: "Ghana",
      ownership_pct: 90,
      type: "Open pit",
      primary_metal: "gold",
      metals: ["gold"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Large open-pit operation."
    },
    {
      name: "Damang",
      location: "Western",
      country: "Ghana",
      ownership_pct: 100,
      type: "Open pit",
      primary_metal: "gold",
      metals: ["gold"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Open-pit gold mine."
    },
    {
      name: "Cerro Corona",
      location: "Cajamarca",
      country: "Peru",
      ownership_pct: 100,
      type: "Open pit",
      primary_metal: "gold",
      metals: ["gold", "copper"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Gold-copper open pit."
    },
    {
      name: "Salares Norte",
      location: "Atacama",
      country: "Chile",
      ownership_pct: 100,
      type: "Open pit",
      primary_metal: "gold",
      metals: ["gold", "silver"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Ramped up 2024; high-altitude open pit."
    }
  ],
  "AU": [
    {
      name: "Obuasi",
      location: "Ashanti",
      country: "Ghana",
      ownership_pct: 100,
      type: "Underground",
      primary_metal: "gold",
      metals: ["gold"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Rebuilt deep underground mine."
    },
    {
      name: "Iduapriem",
      location: "Western",
      country: "Ghana",
      ownership_pct: 100,
      type: "Open pit",
      primary_metal: "gold",
      metals: ["gold"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Multiple open pits."
    },
    {
      name: "Siguiri",
      location: "Siguiri",
      country: "Guinea",
      ownership_pct: 85,
      type: "Open pit",
      primary_metal: "gold",
      metals: ["gold"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Open-pit operations."
    },
    {
      name: "Geita",
      location: "Geita",
      country: "Tanzania",
      ownership_pct: 100,
      type: "Open pit / underground",
      primary_metal: "gold",
      metals: ["gold"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Flagship Tanzanian asset."
    },
    {
      name: "Kibali",
      location: "Haut-Uele",
      country: "Democratic Republic of the Congo",
      ownership_pct: 45,
      type: "Open pit / underground",
      primary_metal: "gold",
      metals: ["gold"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "JV with Barrick; world-class asset."
    },
    {
      name: "Sunrise Dam",
      location: "Western Australia",
      country: "Australia",
      ownership_pct: 100,
      type: "Open pit / underground",
      primary_metal: "gold",
      metals: ["gold"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Large Western Australia operation."
    },
    {
      name: "Tropicana",
      location: "Western Australia",
      country: "Australia",
      ownership_pct: 70,
      type: "Open pit",
      primary_metal: "gold",
      metals: ["gold"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "JV with IGO; open-pit gold."
    },
    {
      name: "Serra Grande",
      location: "Goias",
      country: "Brazil",
      ownership_pct: 100,
      type: "Underground",
      primary_metal: "gold",
      metals: ["gold"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Underground mining complex."
    },
    {
      name: "CuiabÃ¡ / Lamego",
      location: "Minas Gerais",
      country: "Brazil",
      ownership_pct: 100,
      type: "Underground",
      primary_metal: "gold",
      metals: ["gold"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Underground operations in Brazil."
    }
  ],
  "PAAS": [
    {
      name: "La Colorada",
      location: "Zacatecas",
      country: "Mexico",
      ownership_pct: 100,
      type: "Underground",
      primary_metal: "silver",
      metals: ["silver", "gold", "zinc", "lead"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Ag 4,878 koz FY2024; company Ag 21.1 Moz, Au 892.5 koz; Ag AISC $18.98/oz, Au AISC $1,501/oz."
    },
    {
      name: "Huaron",
      location: "Pasco",
      country: "Peru",
      ownership_pct: 100,
      type: "Underground",
      primary_metal: "silver",
      metals: ["silver", "lead", "zinc", "copper"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Ag 3,519 koz FY2024."
    },
    {
      name: "San Vicente",
      location: "PotosÃ­",
      country: "Bolivia",
      ownership_pct: 95,
      type: "Underground",
      primary_metal: "silver",
      metals: ["silver", "zinc", "lead"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Ag 3,109 koz FY2024."
    },
    {
      name: "Cerro Moro",
      location: "Santa Cruz",
      country: "Argentina",
      ownership_pct: 100,
      type: "Underground",
      primary_metal: "silver",
      metals: ["silver", "gold", "lead", "zinc"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Ag 2,969 koz FY2024."
    },
    {
      name: "Jacobina",
      location: "Bahia",
      country: "Brazil",
      ownership_pct: 100,
      type: "Underground",
      primary_metal: "gold",
      metals: ["gold"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 197 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Record 197 koz Au FY2024."
    },
    {
      name: "El PeÃ±Ã³n",
      location: "Antofagasta",
      country: "Chile",
      ownership_pct: 100,
      type: "Underground",
      primary_metal: "gold",
      metals: ["gold", "silver"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 127 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Au 127 koz FY2024."
    },
    {
      name: "Shahuindo",
      location: "Cajamarca",
      country: "Peru",
      ownership_pct: 100,
      type: "Open pit",
      primary_metal: "gold",
      metals: ["gold", "silver"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 135 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Au 135 koz FY2024."
    },
    {
      name: "Timmins",
      location: "Ontario",
      country: "Canada",
      ownership_pct: 100,
      type: "Underground",
      primary_metal: "gold",
      metals: ["gold", "silver"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 124 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Au 124 koz FY2024."
    },
    {
      name: "Minera Florida",
      location: "Metropolitan",
      country: "Chile",
      ownership_pct: 100,
      type: "Underground",
      primary_metal: "gold",
      metals: ["gold", "silver"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 80 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Au 80 koz FY2024."
    },
    {
      name: "Dolores",
      location: "Chihuahua",
      country: "Mexico",
      ownership_pct: 100,
      type: "Heap leach",
      primary_metal: "gold",
      metals: ["gold", "silver"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 72 },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Au 72 koz residual leaching FY2024."
    }
  ],
  "AG": [
    {
      name: "San Dimas",
      location: "Durango",
      country: "Mexico",
      ownership_pct: 100,
      type: "Underground",
      primary_metal: "silver",
      metals: ["silver", "gold", "lead", "zinc"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Primary silver-gold district; Ag 8.4 Moz and Au 157 koz company FY2024."
    },
    {
      name: "Santa Elena",
      location: "Sonora",
      country: "Mexico",
      ownership_pct: 100,
      type: "Underground",
      primary_metal: "silver",
      metals: ["silver", "gold", "lead", "zinc"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "~10.3 Moz AgEq record production FY2024."
    },
    {
      name: "La Encantada",
      location: "Coahuila",
      country: "Mexico",
      ownership_pct: 100,
      type: "Underground",
      primary_metal: "silver",
      metals: ["silver", "gold", "lead", "zinc"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Ag ~2.3 Moz; AISC ~$28.31/oz Ag FY2024."
    },
    {
      name: "Jerritt Canyon",
      location: "Nevada",
      country: "United States",
      ownership_pct: 100,
      type: "Open pit / underground",
      primary_metal: "gold",
      metals: ["gold", "silver"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Gold-focused turnaround asset."
    }
  ],
  "BHP": [
    {
      name: "Escondida",
      location: "Antofagasta",
      country: "Chile",
      ownership_pct: 57.5,
      type: "Open pit",
      primary_metal: "copper",
      metals: ["copper", "gold", "silver"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Cu ~1,100 kt (100% basis) FY2025; world largest copper mine."
    },
    {
      name: "Spence",
      location: "Antofagasta",
      country: "Chile",
      ownership_pct: 100,
      type: "Open pit",
      primary_metal: "copper",
      metals: ["copper"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "SX-EW and sulphide processing; cathode and concentrate production."
    },
    {
      name: "Olympic Dam",
      location: "South Australia",
      country: "Australia",
      ownership_pct: 100,
      type: "Underground",
      primary_metal: "copper",
      metals: ["copper", "uranium", "gold", "silver"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Polymetallic underground mine and processing complex."
    },
    {
      name: "WAIO (Pilbara iron ore)",
      location: "Pilbara",
      country: "Australia",
      ownership_pct: 85,
      type: "Open pit",
      primary_metal: "iron",
      metals: ["iron"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "~290 Mt/yr shipped FY2025; multiple mining hubs."
    },
    {
      name: "BMA metallurgical coal",
      location: "Queensland",
      country: "Australia",
      ownership_pct: 50,
      type: "Open pit / underground",
      primary_metal: "metallurgical coal",
      metals: ["metallurgical coal"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "BHP-Mitsubishi Alliance premium met coal."
    },
    {
      name: "Jansen potash",
      location: "Saskatchewan",
      country: "Canada",
      ownership_pct: 100,
      type: "Development",
      primary_metal: "potash",
      metals: ["potash"],
      status: "Development",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Potash development project (Stage 1)."
    }
  ],
  "RIO": [
    {
      name: "Pilbara iron ore",
      location: "Pilbara",
      country: "Australia",
      ownership_pct: 100,
      type: "Open pit",
      primary_metal: "iron",
      metals: ["iron"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "328.6 Mt shipped FY2024 (100% basis)."
    },
    {
      name: "Kennecott",
      location: "Utah",
      country: "United States",
      ownership_pct: 100,
      type: "Open pit",
      primary_metal: "copper",
      metals: ["copper", "gold", "silver", "molybdenum"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Integrated mine, concentrator, smelter and refinery."
    },
    {
      name: "Oyu Tolgoi",
      location: "South Gobi",
      country: "Mongolia",
      ownership_pct: 66,
      type: "Underground",
      primary_metal: "copper",
      metals: ["copper", "gold", "silver"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Underground ramp-up; consolidated Cu 697 kt company FY2024."
    },
    {
      name: "Resolution Copper",
      location: "Arizona",
      country: "United States",
      ownership_pct: 55,
      type: "Development",
      primary_metal: "copper",
      metals: ["copper", "molybdenum", "silver"],
      status: "Development",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Large-scale development project (Rio 55%)."
    },
    {
      name: "Rincon lithium",
      location: "Salta",
      country: "Argentina",
      ownership_pct: 100,
      type: "Brine",
      primary_metal: "lithium",
      metals: ["lithium"],
      status: "Development",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Brine project; development / ramp."
    },
    {
      name: "IOC (Iron Ore Company of Canada)",
      location: "Labrador / Quebec",
      country: "Canada",
      ownership_pct: 58.7,
      type: "Open pit",
      primary_metal: "iron",
      metals: ["iron"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Concentrate and pellets production."
    },
    {
      name: "Weipa / Gove bauxite",
      location: "Queensland / Northern Territory",
      country: "Australia",
      ownership_pct: 100,
      type: "Open pit",
      primary_metal: "aluminum",
      metals: ["bauxite"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Bauxite mines feeding alumina refineries."
    },
    {
      name: "Kitimat aluminum smelter",
      location: "British Columbia",
      country: "Canada",
      ownership_pct: 100,
      type: "Smelter",
      primary_metal: "aluminum",
      metals: ["aluminum"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Modern AP60 smelter."
    },
    {
      name: "Diavik diamond mine",
      location: "Northwest Territories",
      country: "Canada",
      ownership_pct: 60,
      type: "Open pit / underground",
      primary_metal: "diamonds",
      metals: ["diamonds"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "~60% interest; subarctic diamond mining."
    }
  ],
  "VALE": [
    {
      name: "CarajÃ¡s / Northern System",
      location: "ParÃ¡",
      country: "Brazil",
      ownership_pct: 100,
      type: "Open pit",
      primary_metal: "iron",
      metals: ["iron"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Includes S11D ~83 Mt record contribution; iron ore 328 Mt company FY2024."
    },
    {
      name: "Southeastern System",
      location: "Minas Gerais",
      country: "Brazil",
      ownership_pct: 100,
      type: "Open pit / underground",
      primary_metal: "iron",
      metals: ["iron"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Itabira, Minas Centrais, Mariana hubs; Brucutu expansions."
    },
    {
      name: "Southern System",
      location: "Minas Gerais",
      country: "Brazil",
      ownership_pct: 100,
      type: "Open pit",
      primary_metal: "iron",
      metals: ["iron"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Vargem Grande, Paraopeba, others."
    },
    {
      name: "Salobo",
      location: "ParÃ¡",
      country: "Brazil",
      ownership_pct: 100,
      type: "Open pit",
      primary_metal: "copper",
      metals: ["copper", "gold", "silver", "molybdenum"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Copper-gold; record FY2024 production."
    },
    {
      name: "Voisey's Bay",
      location: "Newfoundland and Labrador",
      country: "Canada",
      ownership_pct: 100,
      type: "Underground / open pit",
      primary_metal: "nickel",
      metals: ["nickel", "copper", "cobalt"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Nickel-copper-cobalt underground expansion."
    },
    {
      name: "Sudbury",
      location: "Ontario",
      country: "Canada",
      ownership_pct: 100,
      type: "Underground",
      primary_metal: "nickel",
      metals: ["nickel", "copper", "PGMs"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Integrated nickel-copper-PGM operations."
    },
    {
      name: "OnÃ§a Puma",
      location: "ParÃ¡",
      country: "Brazil",
      ownership_pct: 100,
      type: "Open pit / furnace",
      primary_metal: "nickel",
      metals: ["nickel"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Ferronickel operation."
    },
    {
      name: "PT Vale Indonesia",
      location: "Sulawesi / Halmahera",
      country: "Indonesia",
      ownership_pct: ,
      type: "Open pit / RKEF",
      primary_metal: "nickel",
      metals: ["nickel"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Pomalaa, Sorowako and partners; nickel for EV supply chain."
    }
  ],
  "ALB": [
    {
      name: "Salar de Atacama",
      location: "Antofagasta",
      country: "Chile",
      ownership_pct: 49,
      type: "Brine",
      primary_metal: "lithium",
      metals: ["lithium"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Brine resource; carbonate and hydroxide chains (~49% economic interest in complex structure)."
    },
    {
      name: "Greenbushes",
      location: "Western Australia",
      country: "Australia",
      ownership_pct: 49,
      type: "Open pit",
      primary_metal: "lithium",
      metals: ["lithium", "tin", "tantalum"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Talison JV; spodumene concentrate."
    },
    {
      name: "Wodgina",
      location: "Western Australia",
      country: "Australia",
      ownership_pct: 60,
      type: "Open pit",
      primary_metal: "lithium",
      metals: ["lithium"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "MARBL JV 60%; spodumene restart/ramp."
    },
    {
      name: "Kemerton",
      location: "Western Australia",
      country: "Australia",
      ownership_pct: 60,
      type: "Conversion",
      primary_metal: "lithium",
      metals: ["lithium"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Hydroxide conversion trains (60%)."
    },
    {
      name: "Silver Peak",
      location: "Nevada",
      country: "United States",
      ownership_pct: 100,
      type: "Brine",
      primary_metal: "lithium",
      metals: ["lithium"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "US brine operation."
    },
    {
      name: "Kings Mountain",
      location: "North Carolina",
      country: "United States",
      ownership_pct: 100,
      type: "Development",
      primary_metal: "lithium",
      metals: ["lithium"],
      status: "Development",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: null,
      notes: "Hard-rock spodumene restart / expansion project."
    }
  ],
  "BVN": [
    {
      name: "El Brocal (Colquijirca)",
      location: "Pasco",
      country: "Peru",
      ownership_pct: 61.43,
      type: "Underground + Open Pit",
      primary_metal: "copper",
      metals: ["copper", "silver", "gold", "zinc", "lead"],
      status: "Operating",
      production: { copper_mlbs: 125, gold_koz: 24, silver_koz: 2123 },
      costs: { aisc_per_lb_cu: 3.00, cash_cost_per_lb: 2.73 },
      reserves: { copper_blbs: null, gold_moz: 1.4, silver_moz: 63.3, copper_kt: 1017 },
      mine_life_yrs: 17,
      notes: "Underground Marcapunta (Cu) + Tajo Norte open pit (Ag/Pb/Zn). Total reserves 81.4 Mt @ 1.22% Cu, 19.6 g/t Ag, 0.59 g/t Au. SLR S-K 1300 NPV $619M (after-tax, 10.18% WACC, conservative prices). Plant capacity 18,000 tpd, expansion to 25,000 tpd pending MEIA approval. FY2024 Cu production 56,525 TMF. 450+ years of continuous mining history. Zero debt, $173.5M cash (FY2025). Resources add 57.8 Mt underground + 2.5 Mt open pit beyond reserves. Active exploration at Esperanza, Bohorquez, MKP SE revealing significant new Cu deposits."
    },
    {
      name: "Orcopampa",
      location: "Arequipa",
      country: "Peru",
      ownership_pct: 100,
      type: "Underground",
      primary_metal: "gold",
      metals: ["gold", "silver"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 71, silver_koz: null },
      costs: { aisc_per_oz: null, cash_cost_per_oz: null },
      reserves: { gold_moz: null },
      mine_life_yrs: null,
      notes: "BVN's flagship gold mine, operating since 1967. Underground epithermal vein system at 3,800 masl. Capacity 1,500 tpd. FY2024 Au production 70,892 oz. Declining grades but still BVN's largest Au producer."
    },
    {
      name: "Tambomayo",
      location: "Arequipa",
      country: "Peru",
      ownership_pct: 100,
      type: "Underground",
      primary_metal: "gold",
      metals: ["gold", "silver"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 34, silver_koz: 1412 },
      costs: { aisc_per_oz: null, cash_cost_per_oz: null },
      reserves: { gold_moz: null },
      mine_life_yrs: null,
      notes: "Underground gold-silver mine in Arequipa region. FY2024 Au production 33,896 oz, Ag 1,412,092 oz. High-altitude operation. Production declining from peak."
    },
    {
      name: "Yumpag",
      location: "Pasco",
      country: "Peru",
      ownership_pct: 100,
      type: "Underground",
      primary_metal: "silver",
      metals: ["silver", "lead", "zinc"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null, silver_koz: 8123 },
      costs: { aisc_per_oz_ag: null },
      reserves: { silver_moz: null },
      mine_life_yrs: null,
      notes: "BVN's top silver producer. FY2024 Ag production 8,123,445 oz. Accounts for >50% of direct silver output. Near Uchucchacua. High-grade silver veins."
    },
    {
      name: "Uchucchacua",
      location: "Oyón, Lima",
      country: "Peru",
      ownership_pct: 100,
      type: "Underground",
      primary_metal: "silver",
      metals: ["silver", "lead", "zinc"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: null, silver_koz: 2364 },
      costs: { aisc_per_oz_ag: null },
      reserves: { silver_moz: null },
      mine_life_yrs: null,
      notes: "Historic silver mine, restarted Q4 2023 after care & maintenance since Q3 2021. FY2024 Ag 2,364,035 oz. Ramping from 800 to 1,500 tpd. Major Pb/Zn producer."
    },
    {
      name: "Julcani",
      location: "Huancavelica",
      country: "Peru",
      ownership_pct: 100,
      type: "Underground",
      primary_metal: "silver",
      metals: ["silver", "gold"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 5, silver_koz: 1403 },
      costs: { aisc_per_oz_ag: null },
      reserves: { silver_moz: null },
      mine_life_yrs: null,
      notes: "Historical polymetallic mine in Huancavelica. FY2024 Au 4,504 oz, Ag 1,402,786 oz. One of Peru's oldest mines."
    },
    {
      name: "La Zanja",
      location: "Cajamarca",
      country: "Peru",
      ownership_pct: 100,
      type: "Open pit (heap leach)",
      primary_metal: "gold",
      metals: ["gold"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 16, silver_koz: null },
      costs: { aisc_per_oz: null, cash_cost_per_oz: null },
      reserves: { gold_moz: null },
      mine_life_yrs: null,
      notes: "Small open-pit gold heap-leach operation. FY2024 Au 15,746 oz. Nearing end of mine life."
    },
    {
      name: "San Gabriel",
      location: "Moquegua",
      country: "Peru",
      ownership_pct: 100,
      type: "Underground",
      primary_metal: "gold",
      metals: ["gold", "silver"],
      status: "Development",
      production: { copper_mlbs: null, gold_koz: 0, silver_koz: null },
      costs: { aisc_per_oz: null, cash_cost_per_oz: null },
      reserves: { gold_moz: 2.7 },
      mine_life_yrs: 10,
      notes: "BVN's key growth project. Underground gold-silver mine. First production expected Q4 2025. Target ~100-120 koz Au/yr at full capacity. Q4 2024 capex $104.8M. Total capex estimate ~$600M. Reserves 2.7 Moz Au."
    },
    {
      name: "Coimolache",
      location: "Cajamarca",
      country: "Peru",
      ownership_pct: 40.09,
      type: "Open pit (heap leach)",
      primary_metal: "gold",
      metals: ["gold"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 25, silver_koz: null },
      costs: { aisc_per_oz: null, cash_cost_per_oz: null },
      reserves: { gold_moz: null },
      mine_life_yrs: null,
      notes: "JV gold heap-leach mine. BVN 40.09% stake. FY2024 attributable ~10 koz Au (total mine ~25 koz). Near La Zanja."
    },
    {
      name: "Yanacocha (equity)",
      location: "Cajamarca",
      country: "Peru",
      ownership_pct: 43.65,
      type: "Open pit + Underground",
      primary_metal: "gold",
      metals: ["gold", "copper", "silver"],
      status: "Operating",
      production: { copper_mlbs: null, gold_koz: 300, silver_koz: null },
      costs: { aisc_per_oz: 1196, cash_cost_per_oz: 1003 },
      reserves: { gold_moz: 12.8 },
      mine_life_yrs: 15,
      notes: "Newmont-operated (NEM 51.35%, BVN 43.65%). Largest gold mine in South America. BVN attributable ~131 koz Au. Yanacocha Sulfides expansion is a major Cu-Au underground project. Total mine FY2024 ~300 koz Au. AISC from NEM filing."
    },
    {
      name: "Cerro Verde (equity)",
      location: "Arequipa",
      country: "Peru",
      ownership_pct: 19.58,
      type: "Open pit",
      primary_metal: "copper",
      metals: ["copper", "molybdenum"],
      status: "Operating",
      production: { copper_mlbs: 949, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: 2.63, net_cash_cost_per_lb: 2.46 },
      reserves: { copper_blbs: null },
      mine_life_yrs: null,
      notes: "Freeport-operated (FCX 55.08%, BVN 19.58%, Sumitomo 21%). Peru's largest Cu mine. BVN received $166.5M dividends in FY2024. Total mine FY2024 Cu 949 Mlbs, Mo ~20 Mlbs. Cash cost from FCX filing."
    }
  ],
  "LAC": [
    {
      name: "Thacker Pass",
      location: "Humboldt County, NV",
      country: "United States",
      ownership_pct: 62,
      type: "Development",
      primary_metal: "lithium",
      metals: ["lithium"],
      status: "Development",
      production: { copper_mlbs: null, gold_koz: null },
      costs: { aisc_per_lb_cu: null, cash_cost_per_lb: null, net_cash_cost_per_lb: null },
      reserves: { copper_blbs: null, gold_moz: null },
      mine_life_yrs: 85,
      notes: "GM JV 38%; ~40,000 tpa LCE nameplate; ~85-year mine life; reserves ~8.0 Mt LCE (company)."
    }
  ]
};
